pkgname="models"
output="models"
debug=false
no-hooks=true
no-tests=false
no-auto-timestamps=false
no-context=true

[mysql]
dbname="sgs_nuyan"
host="10.225.10.194"
port=3306
user="root"
pass=""
sslmode="false"
schema="sgs_nuyan"
blacklist=["migrations"]